/* ---- SATCAT decode tables & family knowledge (curated) ---- */
const OWNER_NAMES={AB:"Arabsat (Arab League)",ABS:"ABS Global",AC:"AsiaSat (Hong Kong)",ALG:"Algeria",ANG:"Angola",ARGN:"Argentina",ASRA:"Austria",AUS:"Australia",AZER:"Azerbaijan",BEL:"Belgium",BELA:"Belarus",BGD:"Bangladesh",BHR:"Bahrain",BOL:"Bolivia",BRAZ:"Brazil",BUL:"Bulgaria",BWA:"Botswana",CA:"Canada",CHBZ:"China / Brazil",CHLE:"Chile",CIS:"Russia (CIS)",CZCH:"Czechia",DEN:"Denmark",DJI:"Djibouti",ECU:"Ecuador",EGYP:"Egypt",ESA:"European Space Agency",ETH:"Ethiopia",EUME:"EUMETSAT",EUTE:"Eutelsat",FIN:"Finland",FR:"France",FRIT:"France / Italy",GER:"Germany",GLOB:"Globalstar",GREC:"Greece",GRSA:"Greece / Saudi Arabia",HRV:"Croatia",HUN:"Hungary",IM:"Inmarsat",IND:"India",INDO:"Indonesia",IRAN:"Iran",IRAQ:"Iraq",ISRA:"Israel",ISS:"ISS partnership",IT:"Italy",ITSO:"Intelsat",JOR:"Jordan",JPN:"Japan",KAZ:"Kazakhstan",KWT:"Kuwait",LAOS:"Laos",LTU:"Lithuania",LUXE:"Luxembourg",MA:"Morocco",MALA:"Malaysia",MEX:"Mexico",MNE:"Montenegro",NETH:"Netherlands",NICO:"Omnispace (New ICO)",NIG:"Nigeria",NKOR:"North Korea",NOR:"Norway",NZ:"New Zealand",O3B:"SES O3b",ORB:"Orbcomm",PAKI:"Pakistan",PERU:"Peru",POL:"Poland",POR:"Portugal",PRC:"China",RASC:"RascomStar-QAF",ROC:"Taiwan",ROM:"Romania",RP:"Philippines",RWA:"Rwanda",SAFR:"South Africa",SAUD:"Saudi Arabia",SES:"SES",SING:"Singapore",SKOR:"South Korea",SLB:"Solomon Islands",SPN:"Spain",STCT:"Singapore / Taiwan",SVK:"Slovakia",SVN:"Slovenia",SWED:"Sweden",SWTZ:"Switzerland",TBD:"To be determined",THAI:"Thailand",TMMC:"Turkmenistan / Monaco",TURK:"Türkiye",UAE:"United Arab Emirates",UK:"United Kingdom",UKR:"Ukraine",US:"United States",VENZ:"Venezuela",VTNM:"Vietnam"};
const SITE_NAMES={AFETR:"Cape Canaveral / KSC",AFWTR:"Vandenberg SFB",DLS:"Dombarovsky (Yasny)",ERAS:"air launch, Eastern Range",FRGUI:"Kourou, French Guiana",JJSLA:"Jeju sea launch, S. Korea",JSC:"Jiuquan, China",KODAK:"Kodiak, Alaska",KSCUT:"Uchinoura, Japan",NSC:"Naro, South Korea",PLMSC:"Plesetsk, Russia",RLLB:"Rocket Lab LC-1, Mahia NZ",SCSLA:"South China Sea platform",SEAL:"Sea Launch platform",SEMLS:"Semnan, Iran",SMTS:"Shahroud, Iran",SRILR:"Sriharikota, India",SVOBO:"Svobodny, Russia",TAISC:"Taiyuan, China",TANSC:"Tanegashima, Japan",TYMSC:"Baikonur, Kazakhstan",VOSTO:"Vostochny, Russia",WLPIS:"Wallops Island, Virginia",WRAS:"air launch, Western Range",WSC:"Wenchang, China",XICLF:"Xichang, China",YSLA:"Yellow Sea platform, China",YUN:"Sohae, North Korea"};
const STATUS_NAMES={"+":"Operational",P:"Partially operational",B:"Backup / standby",S:"Spare",X:"Extended mission",D:"Decayed","":"Unknown","?":"Unknown"};
const FAMS=[
[/^STARLINK/, "Starlink — SpaceX's broadband internet megaconstellation, by far the largest satellite fleet ever flown. Newer craft add direct-to-cell service."],
[/^ONEWEB/, "OneWeb (Eutelsat Group) — UK-based LEO broadband constellation of ~630 satellites in polar orbits."],
[/^KUIPER/, "Project Kuiper — Amazon's LEO broadband constellation, deploying toward ~3,200 satellites."],
[/^QIANFAN/, "Qianfan ('Thousand Sails') — Shanghai-backed Chinese LEO broadband megaconstellation (SSST), planned to reach ~14,000 craft."],
[/^HULIANWANG/, "Hulianwang — satellites of China SatNet's Guowang national LEO broadband constellation."],
[/^(TRANSPORTER|BANDWAGON)/, "Unidentified smallsat riding a SpaceX Transporter/Bandwagon rideshare; awaiting identification in the public catalog."],
[/^OBJECT /, "Recently catalogued object; identity not yet confirmed in the public catalog."],
[/^FLOCK/, "Flock 'Dove' — Planet Labs 3U cubesat, part of the largest Earth-imaging fleet, mapping the whole landmass daily at ~3 m."],
[/^PELICAN/, "Pelican — Planet Labs' next-gen high-resolution, high-revisit imaging satellite."],
[/^SKYSAT/, "SkySat — Planet Labs sub-metre imaging satellite for rapid-revisit tasking."],
[/^LEMUR/, "Lemur-2 — Spire Global cubesat collecting GNSS radio-occultation weather data plus AIS ship and ADS-B aircraft tracking."],
[/^YAOGAN/, "Yaogan — Chinese military remote-sensing series (optical, radar and ELINT missions flown under a civilian designation)."],
[/^COSMOS|^KOSMOS/, "Kosmos — blanket designation for Russian military spacecraft; individual missions span recon, SIGINT, navigation and inspection."],
[/^GEESAT/, "GeeSAT — Geespace (Geely) constellation providing centimetre positioning and IoT links for connected and autonomous vehicles."],
[/^ICEYE/, "ICEYE — Finnish commercial SAR microsatellite imaging day/night through cloud; the largest radar imaging fleet."],
[/^SITRO-AIS/, "Sitro-AIS — Russian Sitronics cubesat for AIS maritime ship tracking."],
[/^CENTISPACE/, "CentiSpace — Beijing Future Navigation LEO satellites augmenting GNSS with centimetre-level correction signals."],
[/^SHIYAN/, "Shiyan — Chinese 'experiment' series for classified technology demonstration."],
[/^SHIJIAN/, "Shijian — Chinese 'practice' series for space technology tests, from power systems to GEO servicing and inspection."],
[/^TJS/, "TJS (Tongxin Jishu Shiyan) — classified Chinese GEO 'communication technology test' satellites, widely assessed as early warning / SIGINT."],
[/^HAWK/, "Hawk — HawkEye 360 formation-flying trios geolocating radio-frequency emitters (ships, jammers, radars) from orbit."],
[/^KINEIS/, "Kinéis — French 25-nanosat constellation for global IoT connectivity, successor to the Argos system."],
[/^TIANQI/, "Tianqi — Guodian Gaoke LEO narrowband IoT data-relay constellation."],
[/^IRIDE/, "IRIDE — Italian government Earth-observation constellation programme run with ESA and ASI."],
[/^ION SCV/, "ION SCV — D-Orbit orbital transfer vehicle that carries and releases cubesats into custom orbits."],
[/^SHERPA/, "Sherpa — Spaceflight Inc. orbital transfer vehicle deploying rideshare payloads."],
[/^JILIN/, "Jilin-1 — Chang Guang Satellite's large commercial Earth-imaging constellation, China's biggest."],
[/^TIANMU/, "Tianmu-1 — Chinese commercial GNSS radio-occultation constellation for weather sounding."],
[/^YUNYAO/, "Yunyao-1 — Chinese commercial constellation collecting GNSS-RO atmospheric soundings and AIS ship data."],
[/^CONNECTA/, "Connecta IoT — Turkish Plan-S nanosatellite IoT connectivity constellation."],
[/^RASSVET/, "Rassvet — Bureau 1440, Russia's prototype LEO broadband constellation ('Russian Starlink')."],
[/^BRO[\s\-]/, "BRO — Unseenlabs cubesat for RF geolocation of ships at sea."],
[/^NUSAT/, "ÑuSat — Satellogic's Aleph-1 constellation for high-frequency multispectral Earth imaging."],
[/^YAM[\s\-]/, "YAM ('Yet Another Mission') — Loft Orbital rideshare bus hosting multiple customer payloads."],
[/^TOMORROW/, "Tomorrow.io — commercial weather constellation flying microwave sounders and precipitation radar."],
[/^WILDFIRE/, "Wildfire-detection smallsat constellation providing rapid thermal-infrared fire alerts."],
[/^CAPELLA/, "Capella — US commercial SAR satellite delivering sub-metre radar imagery day or night."],
[/^QPS-SAR/, "QPS-SAR — Japanese iQPS lightweight synthetic-aperture-radar imaging constellation."],
[/^UMBRA/, "Umbra — US commercial SAR microsatellite with very-high-resolution radar imaging."],
[/^SUPERVIEW/, "SuperView Neo — Chinese commercial very-high-resolution optical imaging constellation."],
[/^SPACEMOBILE|^BLUEBIRD|^BLUEWALKER/, "AST SpaceMobile — huge phased-array satellites providing broadband directly to standard mobile phones."],
[/^TEVEL/, "Tevel — Israeli educational cubesats built by school students (Herzliya Science Center programme)."],
[/^GPS|^NAVSTAR/, "GPS (Navstar) — US Space Force global navigation constellation; ~31 active craft in six MEO planes provide worldwide PNT."],
[/^GLONASS|^COSMOS.*GLONASS/, "GLONASS — Russia's global navigation satellite system, 24 slots in three MEO planes."],
[/^GALILEO|^GSAT0/, "Galileo — the EU's civilian global navigation system, ~30 MEO satellites with metre-level open service."],
[/^BEIDOU/, "BeiDou-3 — China's global navigation system mixing MEO, IGSO and GEO satellites."],
[/^IRNSS|^NAVIC/, "NavIC (IRNSS) — India's regional navigation constellation over the Indian Ocean region."],
[/^QZS/, "QZSS ('Michibiki') — Japan's regional navigation overlay in figure-eight quasi-zenith orbits augmenting GPS over East Asia."],
[/^IRIDIUM/, "Iridium NEXT — 66-satellite crosslinked LEO constellation for global voice/data and satellite phones, plus hosted ADS-B."],
[/^GLOBALSTAR/, "Globalstar — LEO constellation for satellite phones, IoT, and the iPhone's emergency SOS relay."],
[/^ORBCOMM/, "Orbcomm — LEO machine-to-machine messaging and AIS data constellation."],
[/^GONETS/, "Gonets-M — Russian LEO store-and-forward messaging constellation."],
[/^INTELSAT|^IS-\d/, "Intelsat — one of the oldest global GEO fleet operators, carrying video, broadband and government traffic."],
[/^SES-\d/, "SES — Luxembourg-based GEO fleet for broadcast and connectivity."],
[/^O3B/, "O3b — SES's MEO constellation delivering fibre-like low-latency broadband to remote regions ('the Other 3 billion')."],
[/^EUTELSAT/, "Eutelsat — European GEO fleet for broadcast and broadband."],
[/^VIASAT/, "ViaSat — very-high-throughput GEO broadband satellites."],
[/^ECHOSTAR|^JUPITER/, "EchoStar/Hughes Jupiter — GEO high-throughput broadband and broadcast."],
[/^INMARSAT/, "Inmarsat — GEO L-band fleet for maritime, aviation and government mobile connectivity."],
[/^THURAYA/, "Thuraya — UAE GEO mobile-telephony satellites for handheld satphones."],
[/^AMAZONAS/, "Amazonas — Hispasat GEO communications over the Americas and Europe."],
[/^ASTRA/, "SES Astra — GEO direct-to-home television for Europe."],
[/^TDRS/, "TDRS — NASA's Tracking and Data Relay Satellites, the GEO network linking the ISS, Hubble and launch vehicles to the ground."],
[/^LUCH|^OLYMP/, "Luch/Olymp — Russian GEO data-relay and (Olymp) signals-intelligence satellites known for close approaches to other craft."],
[/^TIANLIAN/, "Tianlian — Chinese GEO data-relay network serving crewed missions and LEO satellites."],
[/^WGS/, "WGS — Wideband Global SATCOM, the US military's high-capacity GEO communications backbone."],
[/^AEHF/, "AEHF — US military Advanced Extremely High Frequency satellites for protected, jam-resistant strategic comms."],
[/^MUOS/, "MUOS — US Navy narrowband GEO system giving smartphone-like comms to mobile forces."],
[/^SBIRS|^USA.*SBIRS/, "SBIRS — US Space Force GEO/HEO infrared early-warning satellites detecting missile launches."],
[/^GSSAP/, "GSSAP — US Space Force inspector satellites patrolling near the GEO belt for space surveillance."],
[/^SKYNET/, "Skynet — the UK military's secure GEO communications constellation."],
[/^SICRAL/, "SICRAL — Italian military secure communications satellites."],
[/^GOES/, "GOES — NOAA's geostationary weather satellites keeping continuous watch over the Americas."],
[/^HIMAWARI/, "Himawari — Japan's geostationary weather satellites covering the Asia-Pacific."],
[/^METEOSAT|^MTG-/, "Meteosat — EUMETSAT's geostationary weather satellites over Europe, Africa and the Indian Ocean."],
[/^FENGYUN|^FY-/, "Fengyun — China's civil weather satellite series in GEO and polar orbits."],
[/^NOAA/, "NOAA — US polar-orbiting weather satellites feeding global forecast models."],
[/^METOP/, "MetOp — EUMETSAT polar weather satellites, Europe's contribution to the morning-orbit forecast system."],
[/^METEOR/, "Meteor-M — Russia's polar-orbiting weather satellite series."],
[/^JPSS/, "JPSS — the US next-generation polar weather satellite system."],
[/^SENTINEL/, "Sentinel — the EU Copernicus programme's free-and-open Earth-observation fleet (radar, optical, ocean and atmosphere)."],
[/^LANDSAT/, "Landsat — USGS/NASA series imaging Earth's land continuously since 1972, the longest such record."],
[/^GAOFEN/, "Gaofen — China's civil high-resolution Earth-observation programme."],
[/^HAIYANG/, "Haiyang — Chinese ocean-monitoring satellite series."],
[/^ZIYUAN/, "Ziyuan — Chinese land-resources remote-sensing series."],
[/^CARTOSAT/, "Cartosat — ISRO high-resolution mapping satellites."],
[/^RESOURCESAT|^OCEANSAT|^RISAT|^EOS-\d/, "ISRO Earth-observation satellite for land, ocean or radar imaging."],
[/^WORLDVIEW|^GEOEYE/, "Maxar very-high-resolution commercial imaging satellite — source of much of the sharpest imagery in online maps."],
[/^PLEIADES/, "Pléiades — Airbus very-high-resolution optical imaging satellites."],
[/^SPOT[\s\-]?\d/, "SPOT — Airbus wide-area optical imaging series."],
[/^TERRASAR|^TANDEM|^PAZ/, "TerraSAR-X/TanDEM-X/PAZ — German-Spanish radar imaging formation that produced a global 3-D elevation model."],
[/^COSMO-SKYMED|^CSG/, "COSMO-SkyMed — Italy's dual-use radar imaging constellation."],
[/^ISS \(ZARYA\)|^ISS\b/, "The International Space Station — humanity's continuously crewed orbital laboratory since 2000, a five-agency partnership the size of a football field."],
[/^CSS|^TIANHE|^WENTIAN|^MENGTIAN/, "Tiangong — China's crewed space station, permanently occupied since 2022."],
[/^TIANZHOU/, "Tianzhou — Chinese cargo freighter resupplying the Tiangong station."],
[/^PROGRESS/, "Progress — Russian cargo freighter resupplying the ISS."],
[/^CYGNUS|^S\.S\./, "Cygnus — Northrop Grumman cargo freighter resupplying the ISS."],
[/^CREW DRAGON|^DRAGON/, "SpaceX Dragon — crew or cargo capsule serving the ISS."],
[/^SOYUZ-MS/, "Soyuz — Russia's crewed ferry to the ISS, flying since 1967 in successive versions."],
[/^SHENZHOU/, "Shenzhou — China's crewed spacecraft ferrying taikonauts to Tiangong."],
[/^HST|^HUBBLE/, "The Hubble Space Telescope — NASA/ESA's 2.4 m visible/UV observatory, transforming astronomy since 1990."],
[/^CHANDRA/, "Chandra — NASA's flagship X-ray observatory in a deep elliptical orbit."],
[/^XMM/, "XMM-Newton — ESA's large X-ray observatory."],
[/^FERMI/, "Fermi — NASA gamma-ray space telescope surveying the high-energy sky."],
[/^SWIFT/, "Swift — NASA observatory catching gamma-ray bursts within seconds."],
[/^TESS/, "TESS — NASA's exoplanet-hunting survey telescope in a lunar-resonant orbit."],
[/^AQUA|^TERRA\b/, "NASA flagship Earth-science observatory monitoring climate, clouds, ice and vegetation since the early 2000s."],
[/^AURA\b/, "Aura — NASA atmospheric-chemistry observatory tracking ozone and air quality."],
[/^ICESAT/, "ICESat-2 — NASA laser altimeter measuring ice-sheet and sea-ice height to centimetres."],
[/^GRACE/, "GRACE-FO — twin satellites weighing Earth's water by measuring tiny changes in their separation."],
[/^SWOT/, "SWOT — NASA/CNES radar mission surveying the height of nearly all Earth's surface water."],
[/^JASON|^SENTINEL-6/, "Ocean-altimetry satellite continuing the 30-year sea-level record."],
[/^SDO/, "SDO — NASA's Solar Dynamics Observatory, imaging the Sun continuously from GEO-synchronous orbit."],
[/^GOSAT|^OCO-/, "Greenhouse-gas observatory measuring atmospheric CO₂/CH₄ from orbit."]
];
function famBlurb(name){
  for(const f of FAMS) if(f[0].test(name)) return f[1];
  return null;
}
